# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI
on:
  push:
    branches: ["lendzee"]
  pull_request:
    branches: ["lendzee"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i --force
      - run: npm run build --if-present
      #      - run: npm test
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SERVER_LENDZEE_IP}}
          username: ${{secrets.SERVER_LENDZEE_USERNAME}}
          password: ${{secrets.SERVER_LENDZEE_PASSWORD}}
          script: |
            cd ./creditapp-be
            git pull
            source ~/.nvm/nvm.sh
            npm i --force
            npm run build
            npm run copy-templates
            pm2 restart 0
